services:
  - type: web
    name: CustomGPT  # Replace with your app's name
    env: python
    plan: free  # Use "starter" or "standard" for paid plans
    buildCommand: pip install -r requirements.txt  # Install dependencies
    startCommand: streamlit run app.py --server.port 10000 # Command to start your Streamlit app
    envVars:
      - key: STREAMLIT_SERVER_PORT
        value: 10000  # Port for Streamlit to run on